### PR TITLE
feature: allow empty `sessionId` prop, resulting in using default FS session

### PR DESCRIPTION
**Pull request by iakovmarkov**

### CODE REVIEW

**Comment by needcaffeine** [comment]
Can we get this merged in? Thank you!

**Comment by needcaffeine** [comment]
Is this project still being maintained?

**Comment by iakovmarkov** [comment]
I don't think so. You're better off forking it :(

**Comment by needcaffeine** [comment]
@stikmanw Can I please be added as a maintainer on this repository if you don't have time to actively maintain it? I'd prefer that to forking it and merging in all the proposed fixes in a separate fork.

**Comment by ds17f** [comment]
@needcaffeine can we get this merged?  It seems like this would be of value.

**Pull request closed without merging**
