### PR TITLE
Prettier, Snippet Update, and React 16, Oh My!

### PR DESCRIPTION
**Pull request by mjfaga**
Full story has updated their snippet a bit with better cookie support among other things. This PR addresses updating that snippet to their latest version. 

In doing so, given the protections in place to prevent name spacing conflicts, I also reorganized the tests a bit to separate tests that are dependent on the mock FS namespace, and the ones that are actually responsible for setting it up.

As I ventured down that path, I noticed that my own personal prettier settings were reformatting quite a bit, so I've gone ahead and added prettier to the project along with defaults that match it's current style. That included adding the prettier es-lint overrides to ensure those two things never overlap. The only inconsistency that was uncovered in doing so pertains to `function ()` vs `function()` in the `tests/` files. Since the project uses `function()` everywhere in the `src/` directory, I stuck with that and updated the tests appropriately. _**These changes were applied first before I moved forward with the snippet updates.**_

And last, since there is nothing in here depreciated in React 16, I updated the peerDependencies to include both React 15 & 16.

### CODE REVIEW

**Comment by laugri** [comment]
@stikmanw will you be merging PRs in the future ?

**Comment by wallawe** [comment]
Any reason this hasn't been merged? @stikmanw is this still being maintained? If not, should probably make that clear in the readme

**Comment by mjfaga** [comment]
I'm happy to own this and accept PRs on a go-forward basis if this repo is no longer maintained...

**Comment by wallawe** [comment]
You the man! I branched off of yours anyway so that would be great

edit: first thing I had to was merge this PR on top of yours so it might be a good place to start: https://github.com/stikmanw/react-fullstory-component/pull/10

**Comment by needcaffeine** [comment]
@mjfaga I wrote to @stikmanw asking for maintainer access, but unfortunately got no response. Life sometimes gets in the way. If you decide to own a fork, please consider granting maintainer access to at least one other person.

**Comment by mjfaga** [comment]
@stikmanw I’ll start the process of open sourcing a new fork in May if I don’t hear back. Also happy (and prefer) to be promoted to maintainer of this repo if that works for you. 

Thanks! Mark

**Comment by needcaffeine** [comment]
@mjfaga @wallawe @laugri: I've been added as a collaborator of this project. First thing I've done is merge in this PR, and Travis CI then built it.

What I'm looking at next is that git tag and npm version seem to have a mismatch. i.e. we are currently on git tag 2.1.0, but NPM version 2.1.0 points to tag 2.0.0. I'm reconciling them.

**Comment by mjfaga** [comment]
@needcaffeine I'm happy to help with maintenance of this if you would like - let me know.

**Pull request merged**
